#!/usr/bin/env bash

set -e -o pipefail

git status | grep manuscripts \
     | sed -e 's/\s*//g' \
     | sed -e 's/"//g' \
     | sed -e 's/modified://g' \
     | xargs -I {} npm start {}

git add .
git commit -m "$1"
git push origin main